# Generated by Django 5.2.12 on 2026-08-03 21:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleo', '0001_creacion_del_nucleo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(db_index=True, max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada al proveedor'), ('parcial', 'Recibida en parte'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=12)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('fecha', models.DateField(db_index=True)),
                ('fecha_promesa', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('creado_por', models.CharField(blank=True, default='', max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'órdenes de compra',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=180, unique=True)),
                ('rfc', models.CharField(blank=True, default='', max_length=20)),
                ('contacto', models.CharField(blank=True, default='', max_length=120)),
                ('telefono', models.CharField(blank=True, default='', max_length=80)),
                ('correo', models.CharField(blank=True, default='', max_length=180)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'almacén',
                'verbose_name_plural': 'almacenes',
                'ordering': ['-es_principal', 'nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('es_principal',), name='un_solo_almacen_principal')],
            },
        ),
        migrations.CreateModel(
            name='ListaMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('vigente', models.BooleanField(db_index=True, default=True)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('creado_por', models.CharField(blank=True, default='', max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_materiales', to='nucleo.piezacatalogo')),
            ],
            options={
                'verbose_name': 'lista de materiales',
                'verbose_name_plural': 'listas de materiales',
                'ordering': ['pieza', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=180)),
                ('categoria', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('tipo', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('calibre', models.CharField(blank=True, default='', max_length=40)),
                ('unidad', models.CharField(choices=[('pza', 'Pieza'), ('kg', 'Kilogramo'), ('m', 'Metro'), ('m2', 'Metro cuadrado')], default='pza', max_length=4)),
                ('espesor_mm', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('largo_mm', models.PositiveIntegerField(default=0)),
                ('ancho_mm', models.PositiveIntegerField(default=0)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('densidad', models.DecimalField(decimal_places=3, default=Decimal('7.850'), max_digits=6)),
                ('stock_minimo', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('activo', models.BooleanField(default=True)),
                ('legacy_modelo', models.CharField(blank=True, default='', max_length=40)),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activo', 'categoria', 'tipo', 'nombre'],
                'indexes': [models.Index(fields=['categoria', 'tipo'], name='material_familia_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('legacy_id__isnull', False)), fields=('legacy_modelo', 'legacy_id'), name='material_legacy_unico')],
            },
        ),
        migrations.CreateModel(
            name='LoteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=60)),
                ('colada', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='inventario/certificados/%Y/%m/')),
                ('costo_unitario', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('recibido_en', models.DateField(db_index=True)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.material')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inventario.ordencompra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'lote de material',
                'verbose_name_plural': 'lotes de material',
                'ordering': ['recibido_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.almacen')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.lotematerial')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existencias', to='inventario.material')),
            ],
            options={
                'verbose_name': 'existencia',
                'verbose_name_plural': 'existencias',
                'ordering': ['material', 'lote'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('consumo', 'Consumo en producción'), ('devolucion', 'Devolución a almacén'), ('merma', 'Merma o desperdicio'), ('ajuste', 'Ajuste de inventario'), ('traslado_salida', 'Traslado: salida'), ('traslado_entrada', 'Traslado: entrada'), ('anulacion', 'Anulación de un movimiento')], db_index=True, max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=16)),
                ('costo_unitario', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('actor_username', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('ocurrido_en', models.DateTimeField(db_index=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('clave_idempotencia', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('traslado', models.UUIDField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.almacen')),
                ('anula_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anulado_por', to='inventario.movimientomaterial')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_material', to='nucleo.eventoproduccion')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lotematerial')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.material')),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_material', to='nucleo.motivoevento')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_material', to='nucleo.ordenproduccion')),
            ],
            options={
                'verbose_name': 'movimiento de material',
                'verbose_name_plural': 'movimientos de material',
                'ordering': ['-ocurrido_en', '-id'],
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='inventario.proveedor'),
        ),
        migrations.CreateModel(
            name='RenglonListaMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_pieza', models.DecimalField(decimal_places=6, max_digits=16)),
                ('merma_porcentaje', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='inventario.listamateriales')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.material')),
            ],
            options={
                'verbose_name': 'renglón de lista de materiales',
                'verbose_name_plural': 'renglones de lista de materiales',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RenglonOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=16)),
                ('costo_unitario', models.DecimalField(decimal_places=6, max_digits=16)),
                ('cantidad_recibida', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventario.material')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='inventario.ordencompra')),
            ],
            options={
                'verbose_name': 'renglón de orden de compra',
                'verbose_name_plural': 'renglones de orden de compra',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='listamateriales',
            constraint=models.UniqueConstraint(fields=('pieza', 'version'), name='lista_version_unica'),
        ),
        migrations.AddConstraint(
            model_name='listamateriales',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('pieza',), name='una_lista_vigente_por_pieza'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.UniqueConstraint(fields=('material', 'lote', 'almacen'), name='existencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.UniqueConstraint(condition=models.Q(('lote__isnull', True)), fields=('material', 'almacen'), name='existencia_sin_lote_unica'),
        ),
        migrations.AddConstraint(
            model_name='existencia',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', Decimal('0'))), name='existencia_no_negativa'),
        ),
        migrations.AddIndex(
            model_name='movimientomaterial',
            index=models.Index(fields=['material', 'ocurrido_en'], name='mov_material_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientomaterial',
            index=models.Index(fields=['lote', 'ocurrido_en'], name='mov_lote_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientomaterial',
            index=models.Index(fields=['orden'], name='mov_orden_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotematerial',
            constraint=models.UniqueConstraint(fields=('material', 'codigo'), name='lote_unico_por_material'),
        ),
        migrations.AddConstraint(
            model_name='renglonlistamateriales',
            constraint=models.UniqueConstraint(fields=('lista', 'material'), name='renglon_unico_por_lista'),
        ),
        migrations.AddConstraint(
            model_name='renglonordencompra',
            constraint=models.UniqueConstraint(fields=('orden', 'material'), name='renglon_compra_unico'),
        ),
    ]
