# Generated by Django 5.2.12 on 2026-08-04 18:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0049_apuntedetrabajo'),
        ('inventario', '0002_reserva_de_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientomaterial',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_material', to='catalogos.proyecto'),
        ),
        migrations.CreateModel(
            name='SeguimientoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('solicitado', 'Solicitado a compras'), ('ordenado', 'Pedido al proveedor')], db_index=True, default='pendiente', max_length=12)),
                ('cantidad_pedida', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=16)),
                ('promesa', models.DateField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_compra', to='inventario.material')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'seguimiento de compra',
                'verbose_name_plural': 'seguimientos de compra',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
