# Generated by Django 5.2.12 on 2026-04-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=120)),
                ('sub_area', models.CharField(blank=True, max_length=120)),
                ('integrantes', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['area', 'sub_area', 'nombre'],
            },
        ),
    ]
