# Generated by Django 5.2.12 on 2026-04-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_equipotrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipotrabajo',
            name='estados_json',
            field=models.TextField(default='[]'),
        ),
    ]
