# Generated by Django 5.2.12 on 2026-04-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_colaborador_vigaasignacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vigaasignacion',
            new_name='catalogos_v_viga_in_4ff45e_idx',
            old_name='catalogos_viga_i_8a2308_idx',
        ),
    ]
