# Generated by Django 5.2.12 on 2026-04-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_rename_catalogos_viga_i_8a2308_idx_catalogos_v_viga_in_4ff45e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('Corte', 'Corte'), ('Soldadura', 'Soldadura')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rol',
            field=models.CharField(choices=[('Soldador', 'Soldador'), ('Auxiliar', 'Auxiliar'), ('Pintor', 'Pintor'), ('Operador', 'Operador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vigaasignacion',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.colaborador'),
        ),
        migrations.AddField(
            model_name='vigaasignacion',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.maquina'),
        ),
        migrations.AddConstraint(
            model_name="vigaasignacion",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(colaborador__isnull=False, maquina__isnull=True)
                    | models.Q(colaborador__isnull=True, maquina__isnull=False)
                ),
                name="vigaasignacion_persona_o_maquina",
            ),
        ),
    ]
