# Generated by Django 5.2.12 on 2026-04-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_maquina_alter_colaborador_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotPiezaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=120, unique=True)),
                ('peso_kg', models.FloatField(default=0.0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RobotProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='maquina',
            options={'ordering': ['tipo', '-es_robot', 'nombre']},
        ),
        migrations.AddField(
            model_name='maquina',
            name='es_robot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='robotproduccion',
            name='corte_maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='robot_cortes', to='catalogos.maquina'),
        ),
        migrations.AddField(
            model_name='robotproduccion',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='robot_operaciones', to='catalogos.colaborador'),
        ),
        migrations.AddField(
            model_name='robotproduccion',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.robotpiezacatalogo'),
        ),
        migrations.AddField(
            model_name='robotproduccion',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='robot_produccion', to='catalogos.maquina'),
        ),
    ]
