# Generated by Django 5.2.12 on 2026-04-09 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0010_robotpiezacatalogo_robotproduccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=120)),
                ('producto_normalizado', models.CharField(db_index=True, max_length=120)),
                ('cantidad_objetivo', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Cancelada', 'Cancelada')], db_index=True, default='Abierta', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RobotOrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.PositiveIntegerField(default=1)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.robotpiezacatalogo')),
                ('robot_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='robot_orden_items', to='catalogos.maquina')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogos.robotordenproduccion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='robotproduccion',
            name='orden_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones', to='catalogos.robotordenitem'),
        ),
        migrations.AddConstraint(
            model_name='robotordenitem',
            constraint=models.UniqueConstraint(fields=('orden', 'pieza'), name='robotordenitem_orden_pieza_unique'),
        ),
    ]
