# Generated by Django 5.2.12 on 2026-04-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_robotordenproduccion_robotordenitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaFallaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_sistema', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MaquinaParoMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_sistema', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Energia', 'Corte de energía')], db_index=True, max_length=20)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('registrado_por', models.CharField(blank=True, max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaquinaParo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('registrado_por', models.CharField(blank=True, max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paros', to='catalogos.maquina')),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.maquinaparomotivo')),
                ('evento_planta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paros_maquina', to='catalogos.plantaevento')),
            ],
            options={
                'ordering': ['-inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaquinaFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255)),
                ('registrado_por', models.CharField(blank=True, max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fallas', to='catalogos.maquina')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.maquinafallatipo')),
                ('paro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallas', to='catalogos.maquinaparo')),
            ],
            options={
                'ordering': ['-inicio', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fin__isnull', True)), fields=('maquina',), name='maquinafalla_unique_open_per_machine')],
            },
        ),
        migrations.AddConstraint(
            model_name='maquinaparo',
            constraint=models.UniqueConstraint(condition=models.Q(('fin__isnull', True)), fields=('maquina',), name='maquinaparo_unique_open_per_machine'),
        ),
    ]
