# Generated by Django 5.2.12 on 2026-04-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0012_maquinafallatipo_maquinaparomotivo_plantaevento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerrOrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('Corte', 'Corte'), ('Armado', 'Armado'), ('Soldadura', 'Soldadura'), ('Pintura', 'Pintura')], db_index=True, default='Corte', max_length=20)),
                ('pieza_custom_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('pieza_custom_peso_kg', models.FloatField(default=0.0)),
                ('cantidad_requerida', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HerrOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('nombre_normalizado', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('cantidad_objetivo', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada'), ('Cancelada', 'Cancelada')], db_index=True, default='Abierta', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HerrPiezaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=120, unique=True)),
                ('peso_kg', models.FloatField(default=0.0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HerrProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='robotordenitem',
            name='robotordenitem_orden_pieza_unique',
        ),
        migrations.AddField(
            model_name='robotordenitem',
            name='etapa',
            field=models.CharField(choices=[('Corte', 'Corte'), ('Armado', 'Armado'), ('Soldadura', 'Soldadura'), ('Pintura', 'Pintura')], db_index=True, default='Corte', max_length=20),
        ),
        migrations.AddField(
            model_name='robotordenitem',
            name='pieza_custom_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='robotordenitem',
            name='pieza_custom_peso_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='robotordenproduccion',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='robotordenproduccion',
            name='nombre_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='robotordenproduccion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.proyecto'),
        ),
        migrations.AlterField(
            model_name='robotordenitem',
            name='pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.robotpiezacatalogo'),
        ),
        migrations.AlterField(
            model_name='robotordenproduccion',
            name='producto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='robotordenproduccion',
            name='producto_normalizado',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='robotordenitem',
            constraint=models.UniqueConstraint(condition=models.Q(('pieza__isnull', False)), fields=('orden', 'pieza'), name='robotordenitem_orden_pieza_unique'),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.proyecto'),
        ),
        migrations.AddField(
            model_name='herrordenitem',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogos.herrordenproduccion'),
        ),
        migrations.AddField(
            model_name='herrordenitem',
            name='pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.herrpiezacatalogo'),
        ),
        migrations.AddField(
            model_name='herrproduccion',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='herr_operaciones', to='catalogos.colaborador'),
        ),
        migrations.AddField(
            model_name='herrproduccion',
            name='orden_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producciones', to='catalogos.herrordenitem'),
        ),
        migrations.AddConstraint(
            model_name='herrordenitem',
            constraint=models.UniqueConstraint(condition=models.Q(('pieza__isnull', False)), fields=('orden', 'pieza'), name='herrordenitem_orden_pieza_unique'),
        ),
    ]
