# Generated by Django 5.2.12 on 2026-04-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0013_herrordenitem_herrordenproduccion_herrpiezacatalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotproduccion',
            name='pieza_custom_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='robotproduccion',
            name='pieza_custom_peso_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='robotproduccion',
            name='pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.robotpiezacatalogo'),
        ),
    ]
