# Generated by Django 5.2.12 on 2026-04-10

from django.db import migrations


def _create_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in ["herreria", "herreria_supervision"]:
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("catalogos", "0015_herrordenproduccion_es_individual_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(_create_groups, migrations.RunPython.noop),
    ]

