# Generated by Django 5.2.12 on 2026-04-10 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_create_herreria_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotOrdenAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('Corte', 'Corte'), ('Armado', 'Armado'), ('Soldadura', 'Soldadura'), ('Pintura', 'Pintura')], db_index=True, max_length=20)),
                ('asignado_por', models.CharField(blank=True, max_length=120)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.colaborador')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='catalogos.robotordenproduccion')),
            ],
            options={
                'ordering': ['-asignado_en'],
                'constraints': [models.UniqueConstraint(fields=('orden', 'etapa', 'colaborador'), name='robot_asig_unique')],
            },
        ),
    ]
