# Generated by Django 5.2.12 on 2026-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_robotordenasignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='herrordenproduccion',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='plano_pdf',
            field=models.FileField(blank=True, null=True, upload_to='herreria/planos/'),
        ),
    ]
