# Generated by Django 5.2.12 on 2026-04-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0018_herrordenproduccion_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herrordenproduccion',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='codigo_normalizado',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='fecha_compromiso',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='peso_kg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='pieza_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='prioridad',
            field=models.PositiveSmallIntegerField(db_index=True, default=3),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='total_piezas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='ultimo_cambio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='HerrAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(db_index=True, max_length=30)),
                ('rol', models.CharField(db_index=True, max_length=20)),
                ('vigente', models.BooleanField(db_index=True, default=True)),
                ('asignado_por', models.CharField(blank=True, max_length=120)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.colaborador')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.maquina')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_v2', to='catalogos.herrordenproduccion')),
            ],
            options={
                'ordering': ['-asignado_en'],
            },
        ),
    ]
