# Generated by Django 5.2.12 on 2026-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0024_lasermaterialplaca_calibre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lasermaterialplaca',
            options={'ordering': ['-activo', 'categoria_material', 'tipo_material', 'nombre', 'calibre', 'espesor_mm', 'largo_mm', 'ancho_mm', 'id']},
        ),
        migrations.AddField(
            model_name='lasermaterialplaca',
            name='categoria_material',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='lasermaterialplaca',
            name='tipo_material',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='lasermaterialplaca',
            name='nombre_normalizado',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='lasermaterialplaca',
            constraint=models.UniqueConstraint(fields=('categoria_material', 'tipo_material', 'nombre_normalizado', 'calibre', 'espesor_mm', 'largo_mm', 'ancho_mm'), name='uniq_lasermaterialplaca_signature'),
        ),
    ]
