# Generated by Django 5.2.12 on 2026-04-22 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0025_alter_lasermaterialplaca_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerrEstadoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, default='', max_length=30)),
                ('fecha_operacion', models.DateField(blank=True, db_index=True, null=True)),
                ('actor_username', models.CharField(blank=True, default='', max_length=120)),
                ('motivo_retroceso', models.CharField(blank=True, default='', max_length=255)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='catalogos.herrordenproduccion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
