# Generated by Django 5.2.12 on 2026-04-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0026_herrestadocambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='herrordenproduccion',
            name='cantidad_producida',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='es_op',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='cantidad_producida',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='es_op',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
