# Generated by Django 5.2.12 on 2026-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0027_herrordenproduccion_cantidad_producida_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="herrordenproduccion",
            name="cantidad_pintada",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="herrordenproduccion",
            name="cantidad_terminada",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="laserordenproduccion",
            name="cantidad_pintada",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="laserordenproduccion",
            name="cantidad_terminada",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]

