# Generated by Django 5.2.12 on 2026-04-24 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0029_laserordenproduccion_archivo_dxf'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerrCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=180, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='cliente_herreria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.herrcliente'),
        ),
        migrations.CreateModel(
            name='HerrSolicitudProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Cancelada', 'Cancelada')], db_index=True, default='Pendiente', max_length=20)),
                ('creado_por', models.CharField(blank=True, default='', max_length=120)),
                ('aceptado_por', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('aceptado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.herrcliente')),
                ('orden_creada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.herrordenproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.herrpiezacatalogo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
