# Generated by Django 5.2.12 on 2026-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0030_herrcliente_herrordenproduccion_cliente_herreria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herrsolicitudproduccion',
            name='fecha_compromiso',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
