# Generated by Django 5.2.12 on 2026-04-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0031_herrsolicitudproduccion_fecha_compromiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(db_index=True, max_length=40, unique=True)),
                ('cliente', models.CharField(db_index=True, max_length=180)),
                ('telefono', models.CharField(blank=True, default='', max_length=80)),
                ('fecha_compromiso', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Terminada', 'Terminada'), ('Cancelada', 'Cancelada')], db_index=True, default='Activa', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LogisticaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalogos.herrpiezacatalogo')),
            ],
            options={
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogisticaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('actor', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='catalogos.pedidoproduccion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProduccionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.PositiveIntegerField(default=1)),
                ('apartado', models.PositiveIntegerField(default=0)),
                ('enviado', models.PositiveIntegerField(default=0)),
                ('estado_herreria', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Espera de material', 'Espera de material'), ('En producción', 'En producción'), ('Cancelado', 'Cancelado')], db_index=True, default='Pendiente', max_length=30)),
                ('aceptado_por', models.CharField(blank=True, default='', max_length=120)),
                ('aceptado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('espera_material_entrada_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('espera_material_salida_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden_herreria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.herrordenproduccion')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogos.pedidoproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.herrpiezacatalogo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LogisticaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_in', 'stock_in'), ('apartar', 'apartar'), ('enviar', 'enviar'), ('revertir', 'revertir')], db_index=True, max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('actor', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.herrpiezacatalogo')),
                ('pedido_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.pedidoproduccionitem')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LogisticaEnvioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('revertido', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogos.logisticaenvio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.herrpiezacatalogo')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envio_items', to='catalogos.pedidoproduccionitem')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
