# Generated by Django 5.2.12 on 2026-04-29 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0032_pedidoproduccion_logisticastock_logisticaenvio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerrAvanceCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateField(db_index=True)),
                ('soldadas_prev', models.PositiveIntegerField(default=0)),
                ('soldadas_new', models.PositiveIntegerField(default=0)),
                ('pintadas_prev', models.PositiveIntegerField(default=0)),
                ('pintadas_new', models.PositiveIntegerField(default=0)),
                ('terminadas_prev', models.PositiveIntegerField(default=0)),
                ('terminadas_new', models.PositiveIntegerField(default=0)),
                ('actor_username', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_avance', to='catalogos.herrordenproduccion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
