# Generated by Django 5.2.12 on 2026-04-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0033_herravancecambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproduccion',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
    ]
