# Generated by Django 5.2.12 on 2026-04-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0034_pedidoproduccion_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticaenvio',
            name='comprobante_pdf',
            field=models.FileField(blank=True, null=True, upload_to='logistica/envios/%Y/%m/%d'),
        ),
    ]
