# Generated by Django 5.2.12 on 2026-04-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0035_logisticaenvio_comprobante_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='laserordenproduccion',
            name='apartado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='correo',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='enviado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='folio_externo',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='folio_externo_normalizado',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
