# Generated by Django 5.2.12 on 2026-04-30 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0036_laserordenproduccion_apartado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticaStockCorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=180)),
                ('producto_normalizado', models.CharField(db_index=True, max_length=180, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['producto'],
            },
        ),
        migrations.CreateModel(
            name='LogisticaEnvioCorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('comprobante_pdf', models.FileField(blank=True, null=True, upload_to='logistica/envios_corta/%Y/%m/%d')),
                ('producto', models.CharField(max_length=180)),
                ('producto_normalizado', models.CharField(db_index=True, max_length=180)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('revertido', models.PositiveIntegerField(default=0)),
                ('actor', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistica_envios', to='catalogos.laserordenproduccion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LogisticaMovimientoCorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_in', 'stock_in'), ('apartar', 'apartar'), ('enviar', 'enviar'), ('revertir', 'revertir')], db_index=True, max_length=20)),
                ('producto', models.CharField(max_length=180)),
                ('producto_normalizado', models.CharField(db_index=True, max_length=180)),
                ('cantidad', models.IntegerField(default=0)),
                ('actor', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistica_movimientos', to='catalogos.laserordenproduccion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
