# Generated by Django 5.2.12 on 2026-05-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0038_create_pedidos_ventas_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CortaPiezaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=180, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='corta/catalogo/pdf/%Y/%m/%d')),
                ('dxf', models.FileField(blank=True, null=True, upload_to='corta/catalogo/dxf/%Y/%m/%d')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='laserordenproduccion',
            name='codigo_normalizado',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='corta_pieza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogos.cortapiezacatalogo'),
        ),
    ]
