# Generated by Django 5.2.12 on 2026-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0039_cortapiezacatalogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herrordenproduccion',
            name='cierre_bloqueado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='cierre_estado_previo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='cierre_pendiente_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='cierre_pendiente_hasta',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='cierre_pendiente_por',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='cierre_revertido_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='herrordenproduccion',
            name='cierre_revertido_por',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='cierre_bloqueado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='cierre_estado_previo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='cierre_pendiente_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='cierre_pendiente_hasta',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='cierre_pendiente_por',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='cierre_revertido_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='cierre_revertido_por',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='logisticamovimiento',
            name='tipo',
            field=models.CharField(choices=[('stock_in', 'stock_in'), ('ajuste', 'ajuste'), ('apartar', 'apartar'), ('enviar', 'enviar'), ('revertir', 'revertir')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='logisticamovimientocorta',
            name='tipo',
            field=models.CharField(choices=[('stock_in', 'stock_in'), ('ajuste', 'ajuste'), ('apartar', 'apartar'), ('enviar', 'enviar'), ('revertir', 'revertir')], db_index=True, max_length=20),
        ),
    ]
