# Generated by Django 5.2.12 on 2026-05-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0040_herrordenproduccion_cierre_bloqueado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticaExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generado_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('generado_por', models.CharField(blank=True, default='', max_length=120)),
                ('descargas_count', models.PositiveIntegerField(default=0)),
                ('primera_descarga_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('primera_descarga_por', models.CharField(blank=True, default='', max_length=120)),
                ('ultima_descarga_en', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ultima_descarga_por', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='catalogos.pedidoproduccion')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LogisticaExpedienteDescarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descargado_en', models.DateTimeField(db_index=True)),
                ('usuario', models.CharField(blank=True, default='', max_length=120)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descargas', to='catalogos.logisticaexpediente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente_descargas', to='catalogos.pedidoproduccion')),
            ],
            options={
                'ordering': ['-descargado_en'],
            },
        ),
    ]
