# Generated by Django 5.2.12 on 2026-05-08 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0041_logisticaexpediente_logisticaexpedientedescarga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logisticaexpediente",
            name="pedido",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expediente",
                to="catalogos.pedidoproduccion",
            ),
        ),
        migrations.AddField(
            model_name="logisticaexpediente",
            name="orden_corta",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expediente_logistica",
                to="catalogos.laserordenproduccion",
            ),
        ),
        migrations.AddConstraint(
            model_name="logisticaexpediente",
            constraint=models.CheckConstraint(
                check=(
                    (models.Q(pedido__isnull=False, orden_corta__isnull=True))
                    | (models.Q(pedido__isnull=True, orden_corta__isnull=False))
                ),
                name="logisticaexpediente_exactly_one_target",
            ),
        ),
        migrations.AlterField(
            model_name="logisticaexpedientedescarga",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expediente_descargas",
                to="catalogos.pedidoproduccion",
            ),
        ),
        migrations.AddField(
            model_name="logisticaexpedientedescarga",
            name="orden_corta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expediente_descargas",
                to="catalogos.laserordenproduccion",
            ),
        ),
        migrations.AddConstraint(
            model_name="logisticaexpedientedescarga",
            constraint=models.CheckConstraint(
                check=(
                    (models.Q(pedido__isnull=False, orden_corta__isnull=True))
                    | (models.Q(pedido__isnull=True, orden_corta__isnull=False))
                ),
                name="logisticaexpdescarga_exactly_one_target",
            ),
        ),
    ]
