"""Centros de trabajo con función y capacidad, y cuadrillas dinámicas.

Sólo agrega: tres columnas en `maquina`, dos tablas nuevas y sus
restricciones. Ningún `RemoveField`, ningún `DeleteModel`, ningún `DROP`.

Django quiso meter aquí, además, un tira-y-recrea de dos restricciones de
`logisticaexpediente`. No venía de ningún cambio real: los modelos pasaron de
`check=` a `condition=`, que es el mismo SQL con otro nombre de argumento en
Django 5.2. Se quitaron a mano. Aplicarlo habría soltado y vuelto a poner
restricciones sobre tablas vivas para dejarlas exactamente igual.
"""

# Generated by Django 5.2.12 on 2026-08-04 16:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0045_colaborador_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('completo', 'Jornada completa')], db_index=True, default='completo', max_length=12)),
                ('centro', models.CharField(choices=[('Corte', 'Corte'), ('Soldadura', 'Soldadura'), ('Pintura', 'Pintura')], db_index=True, max_length=20)),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('armada_por', models.CharField(blank=True, default='', max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cuadrilla',
                'verbose_name_plural': 'cuadrillas',
                'ordering': ['-fecha', 'centro', 'turno'],
            },
        ),
        migrations.CreateModel(
            name='CuadrillaIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(blank=True, choices=[('Soldador', 'Soldador'), ('Auxiliar', 'Auxiliar'), ('Pintor', 'Pintor'), ('Operador', 'Operador')], default='', max_length=20)),
                ('fraccion', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
            ],
            options={
                'verbose_name': 'integrante de cuadrilla',
                'verbose_name_plural': 'integrantes de cuadrilla',
                'ordering': ['colaborador__nombre'],
            },
        ),
        migrations.AddField(
            model_name='maquina',
            name='capacidad_hora',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Piezas, metros o kilos por hora. Cero si no se ha medido.', max_digits=10),
        ),
        migrations.AddField(
            model_name='maquina',
            name='capacidad_unidad',
            field=models.CharField(blank=True, default='', help_text='La unidad de la capacidad: pza/h, m/h, kg/h…', max_length=20),
        ),
        migrations.AddField(
            model_name='maquina',
            name='funcion',
            field=models.CharField(blank=True, default='', help_text='Qué corta o suelda este equipo. Ej.: «Placa hasta 25 mm»', max_length=180),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(choices=[('Corte', 'Corte'), ('Soldadura', 'Soldadura'), ('Pintura', 'Pintura')], max_length=20),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuadrillas', to='catalogos.maquina'),
        ),
        migrations.AddField(
            model_name='cuadrilla',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas', to='catalogos.equipotrabajo'),
        ),
        migrations.AddField(
            model_name='cuadrillaintegrante',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='catalogos.colaborador'),
        ),
        migrations.AddField(
            model_name='cuadrillaintegrante',
            name='cuadrilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='catalogos.cuadrilla'),
        ),
        migrations.AddConstraint(
            model_name='cuadrilla',
            constraint=models.UniqueConstraint(fields=('fecha', 'turno', 'centro', 'maquina'), name='cuadrilla_unica_con_maquina'),
        ),
        migrations.AddConstraint(
            model_name='cuadrilla',
            constraint=models.UniqueConstraint(condition=models.Q(('maquina__isnull', True)), fields=('fecha', 'turno', 'centro'), name='cuadrilla_unica_sin_maquina'),
        ),
        migrations.AddConstraint(
            model_name='cuadrillaintegrante',
            constraint=models.UniqueConstraint(fields=('cuadrilla', 'colaborador'), name='integrante_unico'),
        ),
        migrations.AddConstraint(
            model_name='cuadrillaintegrante',
            constraint=models.CheckConstraint(condition=models.Q(('fraccion__gt', Decimal('0')), ('fraccion__lte', Decimal('1'))), name='fraccion_de_jornada_valida'),
        ),
    ]
