# Generated by Django 5.2.12 on 2026-08-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0047_constraints_al_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(choices=[('vigas', 'Estructuras metálicas'), ('herreria', 'Herrería'), ('corta', 'Corta.mx'), ('robotica', 'Robótica')], db_index=True, max_length=12)),
                ('referencia', models.PositiveIntegerField(db_index=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparando', 'Preparando para salir'), ('despachado', 'Despachado')], db_index=True, default='pendiente', max_length=12)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('visto_en', models.DateTimeField(blank=True, null=True)),
                ('despachado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'seguimiento de despacho',
                'verbose_name_plural': 'seguimientos de despacho',
                'ordering': ['-actualizado_en'],
                'constraints': [models.UniqueConstraint(fields=('linea', 'referencia'), name='seguimiento_despacho_unico')],
            },
        ),
    ]
