# Generated by Django 5.2.12 on 2026-08-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0048_seguimiento_de_despacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApunteDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(choices=[('vigas', 'Estructuras metálicas'), ('herreria', 'Herrería'), ('corta', 'Corta.mx'), ('robotica', 'Robótica')], db_index=True, max_length=12)),
                ('referencia', models.PositiveIntegerField(db_index=True)),
                ('codigo', models.CharField(blank=True, default='', max_length=120)),
                ('etapa', models.CharField(db_index=True, max_length=40)),
                ('etapa_anterior', models.CharField(blank=True, default='', max_length=40)),
                ('integrantes', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('ocurrido_en', models.DateTimeField(db_index=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuntes', to='catalogos.cuadrilla')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apuntes', to='catalogos.maquina')),
            ],
            options={
                'verbose_name': 'apunte de trabajo',
                'verbose_name_plural': 'apuntes de trabajo',
                'ordering': ['-ocurrido_en'],
                'indexes': [models.Index(fields=['maquina', 'ocurrido_en'], name='catalogos_a_maquina_1d36b5_idx'), models.Index(fields=['linea', 'referencia'], name='catalogos_a_linea_2b6303_idx')],
            },
        ),
    ]
