# Generated by Django 5.2.12 on 2026-08-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0049_apuntedetrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='laserordenproduccion',
            name='calibre',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='laserordenproduccion',
            name='espesor_mm',
            field=models.FloatField(default=0.0),
        ),
    ]
