"""Los datos de recursos humanos de cada persona.

Sólo AddField, y todo opcional: los colaboradores que ya existen se quedan
como estaban y el sistema sigue funcionando mientras alguien los completa.
"""

# Generated by Django 5.2.12 on 2026-08-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0050_espesor_y_calibre_del_pedido'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='personal.departamento'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='personal.puesto'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer'), ('X', 'Prefiere no decirlo')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='sueldo_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
