# Generated by Django 5.2.12 on 2026-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_creacion_del_nucleo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='ruta',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
