# Generated by Django 5.2.12 on 2026-08-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_ruta_por_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezacatalogo',
            name='especificaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='piezacatalogo',
            name='ruta',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='EspecificacionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_modelo', models.CharField(max_length=40)),
                ('legacy_id', models.PositiveIntegerField()),
                ('texto', models.TextField(blank=True, default='')),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=120)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'especificación de la orden',
                'verbose_name_plural': 'especificaciones de las órdenes',
                'ordering': ['legacy_modelo', 'legacy_id'],
                'constraints': [models.UniqueConstraint(fields=('legacy_modelo', 'legacy_id'), name='especificacion_unica_por_orden')],
            },
        ),
    ]
