# Generated by Django 5.2.12 on 2026-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_ruta_recordada_y_especificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='retirada_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
