# Generated by Django 5.2.12 on 2026-08-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_orden_retirada'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.SlugField(max_length=30)),
                ('producto', models.CharField(max_length=180)),
                ('producto_normalizado', models.CharField(db_index=True, max_length=180)),
                ('minimo', models.PositiveIntegerField(default=0)),
                ('objetivo', models.PositiveIntegerField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=120)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'nivel mínimo de almacén',
                'verbose_name_plural': 'niveles mínimos de almacén',
                'ordering': ['linea', 'producto'],
                'constraints': [models.UniqueConstraint(fields=('linea', 'producto_normalizado'), name='minimo_unico_por_producto')],
            },
        ),
    ]
