# Generated by Django 5.2.12 on 2026-08-05 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0049_apuntedetrabajo'),
        ('nucleo', '0005_nivel_minimo_de_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=180)),
                ('codigo', models.CharField(blank=True, default='', max_length=60)),
                ('codigo_normalizado', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_compromiso', models.DateField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('creado_por', models.CharField(blank=True, default='', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='catalogos.proyecto')),
            ],
            options={
                'verbose_name': 'requerimiento del proyecto',
                'verbose_name_plural': 'requerimientos del proyecto',
                'ordering': ['proyecto', 'descripcion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('codigo_normalizado', ''), _negated=True), fields=('proyecto', 'codigo_normalizado'), name='requerimiento_codigo_unico_por_proyecto')],
            },
        ),
    ]
