# Generated by Django 5.2.12 on 2026-08-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_requerimientos_de_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaDeEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_modelo', models.CharField(max_length=40)),
                ('legacy_id', models.PositiveIntegerField()),
                ('codigo', models.CharField(blank=True, default='', max_length=120)),
                ('area_origen', models.CharField(max_length=40)),
                ('area_destino', models.CharField(max_length=40)),
                ('etapa_origen', models.CharField(blank=True, default='', max_length=40)),
                ('etapa_destino', models.CharField(blank=True, default='', max_length=40)),
                ('entrega_por', models.CharField(db_index=True, max_length=150)),
                ('entrega_firma', models.TextField(blank=True, default='')),
                ('entregado_en', models.DateTimeField(db_index=True)),
                ('recibe_por', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('recibe_firma', models.TextField(blank=True, default='')),
                ('recibido_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Esperando a que la reciban'), ('aceptada', 'Recibida y firmada'), ('rechazada', 'Devuelta')], db_index=True, default='pendiente', max_length=12)),
                ('motivo', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'acta de entrega',
                'verbose_name_plural': 'actas de entrega',
                'ordering': ['-entregado_en'],
                'indexes': [models.Index(fields=['legacy_modelo', 'legacy_id', 'entregado_en'], name='nucleo_acta_legacy__3790f8_idx'), models.Index(fields=['estado', 'entregado_en'], name='nucleo_acta_estado_126c64_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('legacy_modelo', 'legacy_id'), name='una_entrega_pendiente_por_pieza')],
            },
        ),
    ]
