# Generated by Django 5.2.12 on 2026-04-06 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viga',
            fields=[
                ('internal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_viga', models.CharField(db_index=True, max_length=80)),
                ('pieza_no', models.PositiveIntegerField(default=1)),
                ('total_piezas', models.PositiveIntegerField(default=1)),
                ('proyecto', models.CharField(blank=True, db_index=True, max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_compromiso', models.DateField(blank=True, db_index=True, null=True)),
                ('estado', models.CharField(db_index=True, max_length=40)),
                ('observaciones', models.TextField(blank=True)),
                ('prioridad', models.IntegerField(db_index=True, default=0)),
                ('peso_kg', models.FloatField(default=0)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_cambio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vigas',
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, max_length=40)),
                ('estado_nuevo', models.CharField(max_length=40)),
                ('fecha_operacion', models.DateField(db_index=True)),
                ('comentario', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('viga_internal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='produccion.viga')),
            ],
            options={
                'db_table': 'production_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
