# Generated by Django 5.2.12 on 2026-04-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='viga',
            options={'managed': False},
        ),
    ]
