# Generated by Django 5.2.12 on 2026-08-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=120)),
                ('rol_de_produccion', models.CharField(blank=True, choices=[('Soldador', 'Soldador'), ('Auxiliar', 'Auxiliar'), ('Pintor', 'Pintor'), ('Operador', 'Operador')], default='', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='personal.departamento')),
            ],
            options={
                'verbose_name': 'puesto',
                'verbose_name_plural': 'puestos',
                'ordering': ['-activo', 'departamento__nombre', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre_normalizado', 'departamento'), name='uniq_puesto_por_departamento')],
            },
        ),
    ]
