# Generated by Django 5.2.12 on 2026-08-03 21:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0044_tipos_de_movimiento_por_destino'),
        ('nucleo', '0001_creacion_del_nucleo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('horas_max_por_visita', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centros_costo', to='nucleo.lineanegocio')),
            ],
            options={
                'verbose_name': 'centro de costo',
                'verbose_name_plural': 'centros de costo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CostoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('absorcion', 'Absorbente (incluye indirectos)'), ('directo', 'Directo (sólo material, obra y máquina)')], default='absorcion', max_length=12)),
                ('material', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('mano_obra', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('maquina', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('overhead', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('horas_maquina', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('horas_persona', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('horas_transcurridas', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('costo_estandar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('horas_estandar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('cobertura', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costo', to='nucleo.ordenproduccion')),
            ],
            options={
                'verbose_name': 'costo de orden',
                'verbose_name_plural': 'costos de orden',
                'ordering': ['-calculado_en'],
            },
        ),
        migrations.CreateModel(
            name='CostoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_transcurridas', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('horas', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('horas_descontadas_por_paro', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('topada', models.BooleanField(default=False)),
                ('personas', models.PositiveSmallIntegerField(default=0)),
                ('mano_obra', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('maquina', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('overhead', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('horas_estandar', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('avisos', models.JSONField(blank=True, default=list)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nucleo.etapa')),
                ('costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='costeo.costoorden')),
            ],
            options={
                'verbose_name': 'costo por etapa',
                'verbose_name_plural': 'costos por etapa',
                'ordering': ['etapa__orden'],
                'constraints': [models.UniqueConstraint(fields=('costo', 'etapa'), name='costo_etapa_unico')],
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField(db_index=True)),
                ('costo_hora_maquina', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('costo_hora_mano_obra', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('overhead_hora', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('creado_por', models.CharField(blank=True, default='', max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='costeo.centrocosto')),
            ],
            options={
                'ordering': ['centro', '-vigente_desde'],
                'constraints': [models.UniqueConstraint(fields=('centro', 'vigente_desde'), name='tarifa_unica_por_fecha')],
            },
        ),
        migrations.CreateModel(
            name='TarifaManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('vigente_desde', models.DateField(db_index=True)),
                ('costo_hora', models.DecimalField(decimal_places=4, max_digits=12)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_costeo', to='catalogos.colaborador')),
            ],
            options={
                'verbose_name': 'tarifa de mano de obra',
                'verbose_name_plural': 'tarifas de mano de obra',
                'ordering': ['-vigente_desde'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('colaborador__isnull', False)), fields=('colaborador', 'vigente_desde'), name='tarifa_persona_unica_por_fecha'), models.UniqueConstraint(condition=models.Q(('colaborador__isnull', True)), fields=('rol', 'vigente_desde'), name='tarifa_rol_unica_por_fecha')],
            },
        ),
        migrations.CreateModel(
            name='TiempoEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_por_pieza', models.DecimalField(decimal_places=4, max_digits=10)),
                ('operadores', models.PositiveSmallIntegerField(default=1)),
                ('vigente_desde', models.DateField(db_index=True)),
                ('notas', models.CharField(blank=True, default='', max_length=255)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_estandar', to='nucleo.etapa')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_estandar', to='nucleo.piezacatalogo')),
            ],
            options={
                'verbose_name': 'tiempo estándar',
                'verbose_name_plural': 'tiempos estándar',
                'ordering': ['pieza', 'etapa__orden', '-vigente_desde'],
                'constraints': [models.UniqueConstraint(fields=('pieza', 'etapa', 'vigente_desde'), name='tiempo_estandar_unico')],
            },
        ),
    ]
