# Generated by Django 5.2.12 on 2026-08-05 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digitos', models.CharField(max_length=8, unique=True)),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=150)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PIN de acceso',
                'verbose_name_plural': 'PINes de acceso',
                'ordering': ['digitos'],
            },
        ),
    ]
